name: Snyk Code Test from reusable workflow


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  code-scan:
    uses: ./.github/workflows/test-gha.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
