name: Snyk Code Test from reusable workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  code-scan:
    uses: ./.github/workflows/snyk-reuse-main.yml
    with:
      solution: ./server/package.json
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
