name: Snyk Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  sast-scan:
    runs-on: ubuntu-latest
    name: Snyk Scans
    steps:     
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
